---
title: "p8105_hw1_xf2290"
author: "Xiwei Fu"
output: github_document
date: "2025-09-21"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(moderndive)
library(ggplot2) 
library(tidyverse)#load packages
data("early_january_weather") #load dataset
```
Short description of the dataset
This dataset is hourly meteorological data for LGA, JFK and EWR for the month of January 2013, which includes 358 rows representing hourly measurements and 15 variables.
The variables are:
origin, year, month, day, hour, temp, dewp, humid, wind_dir, wind_speed, wind_gust, precip, pressure, visib, time_hour.

```{r}
mean(early_january_weather %>% pull(temp))
```
We have the mean temperature is 39.58212 F.
```{r}
ggplot(early_january_weather, aes(x = time_hour, y = temp, color = humid)) +
  geom_point() +
  labs(
    title = "Temperature vs Time in Early January 2013",
    x = "Time (hourly observations)",
    y = "Temperature (°F)",
    color = "Humidity (%)"
  ) 
ggsave("temp_plot.png")
```

```{r}
df <- tibble(
  norm_sample = rnorm(10),                          # numeric
  if_positive = rnorm(10) > 0,                      # logical vector
  char_vec    = sample(letters[1:3], 10, replace=TRUE), # character vector
  fact_vec    = factor(sample(c("low","med","high"), 10, replace=TRUE)) # factor vecotr
)
```


